#!/bin/bash
#
# This script can be run to start the docker container. It requires a single
# directory at the start that contains a file *.Rds. This file will be used
# as the database. The script will create a directory tree in this directory
# and store all volotile data for DEAP in this directory.
# Subsequent calls to run should re-use the initially created container to
# make data available across different runs and instances of DEAP.
#

image_name=$1
container_name=$2
port=$3
data_rds=$4

# use different docker instance names for different ports
USAGE="Usage: run <docker image> <docker instance name> <port> <data path>"

if [[ $# -eq 4 ]]; then
    docker run -d \
               --name ${container_name} \
               -p ${port}:80 \
               -v ${data_rds}:/var/www/html/data/ABCD \
               ${image_name} \
               start
else
    echo ${USAGE}
fi
